local Picker = require("fuzzy.picker")
local picker = Picker.new()

local tt = {
    { name = "test1", },
    { name = "test2", },
    { name = "test3", },
    { name = "test4", },
    { name = "test5", },
    { name = "test6", },
    { name = "test7", },
    { name = "test8", },
    { name = "test9", },
    { name = "test10", },
    { name = "test11", },
    { name = "test12", },
    { name = "test13", },
    { name = "test14", },
    { name = "test15", },
    { name = "test16", },
    { name = "test17", },
    { name = "test18", },
    { name = "test19", },
    { name = "test20", },
    { name = "test21", },
    { name = "test22", },
    { name = "test23", },
    { name = "test24", },
    { name = "test25", },
    { name = "test26", },
    { name = "test27", },
    { name = "test28", },
    { name = "test29", },
    { name = "test30", },
    { name = "test31", },
    { name = "test32", },
    { name = "test33", },
    { name = "test34", },
    { name = "test35", },
    { name = "test36", },
    { name = "test37", },
    { name = "test38", },
    { name = "test39", },
    { name = "test40", },
    { name = "test41", },
    { name = "test42", },
    { name = "test43", },
    { name = "test44", },
    { name = "test45", },
    { name = "test46", },
    { name = "test47", },
    { name = "test48", },
    { name = "test49", },
    { name = "test50", },
    { name = "test51", },
    { name = "test52", },
    { name = "test53", },
    { name = "test54", },
    { name = "test55", },
    { name = "test56", },
    { name = "test57", },
    { name = "test58", },
    { name = "test59", },
    { name = "test60", },
    { name = "test61", },
    { name = "test62", },
    { name = "test63", },
    { name = "test64", },
    { name = "test65", },
    { name = "test66", },
    { name = "test67", },
    { name = "test68", },
    { name = "test69", },
    { name = "test70", },
    { name = "test71", },
    { name = "test72", },
    { name = "test73", },
    { name = "test74", },
    { name = "test75", },
    { name = "test76", },
    { name = "test77", },
    { name = "test78", },
    { name = "test79", },
    { name = "test80", },
    { name = "test81", },
    { name = "test82", },
    { name = "test83", },
    { name = "test84", },
    { name = "test85", },
    { name = "test86", },
    { name = "test87", },
    { name = "test88", },
    { name = "test89", },
    { name = "test90", },
    { name = "test91", },
    { name = "test92", },
    { name = "test93", },
    { name = "test94", },
    { name = "test95", },
    { name = "test96", },
    { name = "test97", },
    { name = "test98", },
    { name = "test99", },
    { name = "test100" },
    { name = "test101" },
}

local function print_50_lines(cb)
    for i = 1, 500000 do
        cb("line " .. i)
    end
    -- cb(nil)
end

vim.keymap.set("n", "gz", function()
    -- picker:open("find", { interactive = false, args = { vim.fn.getcwd(), "-type", "f" } })
    -- picker:open("rg", { args = { }, interactive = true })
    -- picker:open("find", { interactive = "{prompt}", args = { vim.fn.getcwd(), "-type", "f", "-name", "{prompt}" } })
    picker:open(print_50_lines, {})
    -- picker:open(tt, { display = function(e) return e.name end })
end)
