vim.keymap.set("n", "gz", function()
    -- require("fuzzy.sources.buffer").buffers({})
    -- require("fuzzy.sources.files").files({})
    -- require("fuzzy.sources.files").dirs({})
    -- require("fuzzy.sources.files").ls({})
    require("fuzzy.sources.files").grep({})
end)
