local M = {}

M.tests = {
    require("tests.match_spec"),
    require("tests.stream_spec"),
    require("tests.select_spec"),
    require("tests.picker_spec"),
    require("tests.files_spec"),
    require("tests.grep_spec"),
    require("tests.oldfiles_spec"),
    require("tests.tabs_spec"),
    require("tests.lines_spec"),
    require("tests.blines_spec"),
    require("tests.marks_spec"),
    require("tests.jumps_spec"),
    require("tests.changes_spec"),
    require("tests.registers_spec"),
    require("tests.keymaps_spec"),
    require("tests.commands_spec"),
    require("tests.command_history_spec"),
    require("tests.search_history_spec"),
    require("tests.quickfix_spec"),
    require("tests.loclist_spec"),
    require("tests.quickfix_stack_spec"),
    require("tests.loclist_stack_spec"),
    require("tests.helptags_spec"),
    require("tests.manpages_spec"),
    require("tests.vimdoc_spec"),
    require("tests.tags_spec"),
    require("tests.btags_spec"),
    require("tests.colorscheme_spec"),
    require("tests.spell_suggest_spec"),
    require("tests.registry_spec"),
    require("tests.git_spec"),
    require("tests.uiselect_spec"),
    require("tests.scheduler_spec"),
    require("tests.pool_spec"),
    require("tests.init_spec"),
}

return M
